apiVersion: v1
kind: Pod
metadata:
  name: logcreator 
  namespace: assignment
spec:
  containers:
  - name: logcreator 
    image: klemenstanic/log_creator 
    env:
    - name: ELASTIC_PASS
      valueFrom:
        secretKeyRef:
          name: assignment-es-elastic-user
          key: elastic
    imagePullPolicy: Always
