apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: assignment
  labels:
    app.kubernetes.io/name: eck-logstash
    app.kubernets.io/component: logstash
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
